version: "3.9"

services:
  server:
    build:
      context: .
    container_name: corpconnect-server
    restart: always

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      NODE_ENV: production

    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: corpconnect-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  n8n:
    image: n8nio/n8n:latest
    container_name: corpconnect-n8n
    restart: always

    ports:
      - "5678:5678"

    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_ADMIN_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_ADMIN_PASSWORD:-changeme}

      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=dpg-d7j01ilckfvc73ff3cdg-a.singapore-postgres.render.com
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=corp_connect_s4f0
      - DB_POSTGRESDB_USER=corp_connect_s4f0_user
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

      - WEBHOOK_URL=${N8N_WEBHOOK_BASE_URL:-http://localhost:5678}

    volumes:
      - n8n_data:/home/node/.n8n

    depends_on:
      - redis

volumes:
  redis_data:
  n8n_data: